# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
- group: certs-var-group

demands:
- agent.name -equals morpehus

steps:

#- task: AzureKeyVault@1
#  inputs:
#    azureSubscription: 'Visual Studio Enterprise Subscription – MPN(90964ca6-bc75-4398-9fa2-75c890c373cf)'
#    KeyVaultName: 'certs-keyvault-test'
#    SecretsFilter: '*'
#    RunAsPreJob: false
    

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Write-Host $(test-certificate)

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Write-Host $(vmadmin)
